/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 controller.gltf --transform
Author: LockyFarrell (https://sketchfab.com/lockyfarrell3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/akai-midi-controller-89eae01d0547430bb8e10110eaadaa81
Title: AKAI MIDI Controller
*/

import React, { useRef } from 'react';
import { useGLTF } from '/@react-three/drei';

export function Controller(props) {
  const { nodes, materials } = useGLTF('./assets/controller-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.96, 0.91, -2.07]} rotation={[0.1, 0, 0]} scale={[0.48, 0.07, 0.48]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.006']} />
      </group>
      <group position={[2.38, 0.9, -2.05]} rotation={[0.1, 0, 0]} scale={0.23}>
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.42, 0.69, -0.53]} rotation={[0.1, 0, 0]} scale={[0.29, 0.09, 0.15]}>
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.011']} />
      </group>
      <group position={[3.33, 0.69, -0.53]} rotation={[0.1, 0, 0]} scale={[0.29, 0.09, 0.15]}>
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Material.010']} />
      </group>
      <group position={[-4.84, 0.84, -2.05]} rotation={[0, 0, -Math.PI / 2]} scale={[0.38, 0.06, 0.38]}>
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-4.81, 0.69, -0.75]} rotation={[0.1, 0, 0]} scale={[0.29, 0.09, 0.15]}>
        <mesh geometry={nodes.Object_24.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material.020']} />
      </group>
      <group position={[0.04, -0.03, 0]} scale={[6.14, 0.24, 3.06]}>
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material.018']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[-4.6, 0.42, 1.18]} scale={[0.2, 0.12, 1.14]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} position={[-4.99, 0.27, 1.55]} scale={[0.33, 0.18, 1.51]} />
    </group>
  )
}

useGLTF.preload('./assets/controller-transformed.glb')
