/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 laptop.gltf --transform
Author: Aullwen (https://sketchfab.com/Aullwen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-7d870e900889481395b4a575b9fa8c3e
Title: Laptop
*/

import React, { useRef } from 'react';
import { useGLTF } from '/@react-three/drei';

export function Laptop(props) {
  const { nodes, materials } = useGLTF('./assets/laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Frame_ComputerFrame_0.geometry} material={materials.ComputerFrame} position={[0, 0.98, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={40} />
      <mesh geometry={nodes.Screen_ComputerScreen_0.geometry} material={materials.ComputerScreen} position={[0, 0.65, -4.2]} rotation={[Math.PI, 0, -Math.PI]} scale={[40, 40, 10.24]} />
    </group>
  )
}

useGLTF.preload('./assets/laptop-transformed.glb');


