/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 typewriter.gltf --transform
Author: Francesco Coldesina (https://sketchfab.com/topfrank2013)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/typewriter-f8339a2f7ea849b8afbebb76a40e1759
Title: Typewriter
*/

import React, { useRef } from 'react';
import { useGLTF } from '../@react-three/drei';

export function Typewriter(props) {
  const { nodes, materials } = useGLTF('./assets/typewriter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Neri_Royal_typewriter_Plastic_0.geometry} material={materials.Royal_typewriter_Plastic} />
        <mesh geometry={nodes.Neri_Metal_Chrome_0.geometry} material={materials.Metal_Chrome} />
        <mesh geometry={nodes.Neri_Royal_typewriter_Rubber_0.geometry} material={materials.Royal_typewriter_Rubber} />
        <mesh geometry={nodes.Neri_Royal_typewriter_Buttons_0.geometry} material={materials.Royal_typewriter_Buttons} />
        <mesh geometry={nodes.Neri_Royal_typewriter_Metal_black_0.geometry} material={materials.Royal_typewriter_Metal_black} />
        <mesh geometry={nodes.Neri_Royal_typewriter_Measure_0.geometry} material={materials.Royal_typewriter_Measure} />
        <mesh geometry={nodes.Neri_Royal_typewriter_Tape_0.geometry} material={materials.Royal_typewriter_Tape} />
        <mesh geometry={nodes.Neri_Royal_typewriter_Paper_0.geometry} material={materials.Royal_typewriter_Paper} />
      </group>
      <mesh geometry={nodes['Targa_Material_#51_0'].geometry} material={materials.Material_51} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Logo_Royal_typewriter_Label_0.geometry} material={materials.Royal_typewriter_Label} position={[0, 13.95, 11.37]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Bodymy01_17_-_Default_0'].geometry} material={materials['17_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./assets/typewriter-transformed.glb');
